/* ============================================================================
 * FIELD NOTES — LESSONS, both grades
 * ----------------------------------------------------------------------------
 * 72 lessons per grade, 144 in all. Each week has two:
 *
 *   a  INVESTIGATE — question, materials, numbered steps, notebook entry.
 *      Not graded. `supervision:true` means an adult should be present, and
 *      that flag is on every lesson involving heat, glass, staining, biological
 *      samples, sharp tools or going outside alone.
 *
 *   b  EXPLAIN — a short reading, then one claim-with-evidence to write.
 *      The auto-graded check lives in science-quiz.js.
 *
 * WHY THE READING IS SHORT. Georgia's practices standards ask children to
 * argue from evidence, keep unaltered records, and separate observation from
 * guess. Those are habits, not facts, and they are built by doing the
 * investigation and writing the claim — not by reading more text. So Day B's
 * reading is deliberately a few sentences that name the idea the child already
 * met with their hands on Day A.
 *
 * THE CLAIM PROMPT IS THE POINT. Every Day B ends with a claim-evidence
 * sentence, because that is the exact form the standards keep asking for and
 * the exact thing a multiple-choice question cannot test. It is written by
 * hand in the notebook and read by a person.
 * ==========================================================================*/
(function(){

  const Y3 = {
  1:{a:{q:"Can I tell these eight rocks apart using only my eyes and fingers?",
        materials:["8 rocks from outside","hand lens","paper and pencil"],
        steps:["Lay the rocks out and number them 1 to 8.","For each one write its colour in your own words - not just 'grey' but 'grey with white specks'.","Rub a thumb over each and write rough, smooth, or grainy.","Sort them into two piles any way you like, then write the rule you used."],
        notebook:"Draw two of your rocks carefully. Write one sentence saying how they are different.",
        supervision:false},
     b:{read:"Rocks have properties you can observe without any tools: colour, and texture, which is how the surface feels. Scientists start here because these are things anyone can check. If you say a rock is rough, someone else can pick it up and agree or disagree. That is what makes it evidence rather than an opinion.",
        claim:"Pick one rock. Write: 'This rock is ___ because I observed ___.'"}},
  2:{a:{q:"Does a rock look different when it is wet?",
        materials:["your 8 rocks","cup of water","paper towel"],
        steps:["Look at each rock dry and write shiny or dull.","Wet each one and look again.","Write down which rocks changed and which did not."],
        notebook:"Which rock changed the most when wet? Draw it dry and wet.",
        supervision:false},
     b:{read:"Lustre means how a rock catches light. Some rocks look glassy or metallic; others look flat and dull no matter what. Water fills the tiny pits on a rough surface, so a dull rock can look shiny while wet. That is why geologists describe lustre on a dry rock.",
        claim:"Write: 'Rock ___ has a ___ lustre, because when it was dry it ___.'"}},
  3:{a:{q:"Which of my rocks is hardest?",
        materials:["your 8 rocks","fingernail","copper penny","iron nail"],
        steps:["Try to scratch each rock with your fingernail. Record yes or no.","Try the penny on the ones your nail could not scratch.","Try the nail on whatever is left.","Order the rocks from softest to hardest."],
        notebook:"List your rocks in hardness order. Which surprised you?",
        supervision:false},
     b:{read:"Hardness means how well a rock resists being scratched. A harder material scratches a softer one, never the other way round. Mohs built a scale on exactly this idea. A fingernail is about 2.5, a penny about 3.5, an iron nail about 5.5 - so what a tool can and cannot scratch tells you roughly where a rock sits.",
        claim:"Write: 'Rock ___ is harder than rock ___ because ___.'"}},
  4:{a:{q:"Can I sort my rocks by all four properties at once?",
        materials:["your 8 rocks","hand lens","scratch tools","a large sheet of paper"],
        steps:["Draw a table with five columns: rock, colour, texture, lustre, hardness.","Fill in every box for all eight rocks.","Now group the rocks so that each group shares at least two properties.","Write the rule for each group."],
        notebook:"Draw your table. Circle the group you are most confident about.",
        supervision:false},
     b:{read:"Sorting by one property is easy; sorting by four is where it becomes science. Real classification uses several properties together, because any single one can mislead. Two rocks can share a colour and be nothing alike. When you can say why a group belongs together, you have made a claim someone else can test.",
        claim:"Write: 'These rocks belong in the same group because they share ___ and ___.'"}},
  5:{a:{q:"How are sand, clay and loam different to touch?",
        materials:["sand","clay soil","potting soil or loam","3 paper plates","water in a dropper"],
        steps:["Put a spoonful of each soil on its own plate.","Feel each one dry. Write gritty, sticky, or crumbly.","Add three drops of water to each and try to roll a ball.","Write which soils held a ball shape and which fell apart."],
        notebook:"Draw each soil. Write one word for how each felt.",
        supervision:false},
     b:{read:"Soil is not all the same. Sand is made of large grains you can feel separately. Clay is made of grains so small they stick together and hold a shape when wet. Loam is a mixture, with some of each plus decayed plant material. Those differences decide almost everything else about a soil.",
        claim:"Write: 'The ___ soil felt ___, which tells me its grains are ___.'"}},
  6:{a:{q:"Which soil holds water and which lets it run through?",
        materials:["3 cups with holes in the bottom","sand, clay, loam","3 catch cups","measuring cup","water","timer"],
        steps:["Fill each holed cup with the same amount of one soil.","Set each over a catch cup.","Pour the same amount of water into each and start the timer.","After two minutes, measure how much water came through each."],
        notebook:"Make a table: soil, water poured in, water that came out, time. Which held the most?",
        supervision:false},
     b:{read:"Water moves through big gaps quickly and small gaps slowly. Sand has large grains and large gaps, so water pours straight through. Clay has tiny grains packed close, so water is held or barely moves. Loam sits in between, which is why it drains but does not dry out at once.",
        claim:"Write: 'The ___ soil held the most water because ___.'"}},
  7:{a:{q:"Will a bean grow the same in every soil?",
        materials:["3 cups","sand, clay, loam","3 bean seeds","water","ruler","sunny windowsill"],
        steps:["Plant one bean about two centimetres deep in each soil.","Give all three the same water and the same light.","Label each cup and put them side by side.","Water equally every second day and wait."],
        notebook:"Draw the three cups today. Predict which will grow best and write why.",
        supervision:false},
     b:{read:"A seed needs water, air and something to anchor its roots. Sand drains so fast that roots dry out. Clay holds water but packs so tightly that roots struggle to push through and air cannot reach them. Loam holds enough water, lets some drain, and stays loose enough for roots. Most garden plants do best in loam for exactly those reasons.",
        claim:"Write: 'I predict the bean in ___ will grow best because ___.'"}},
  8:{a:{q:"What actually happened to my beans?",
        materials:["your three cups","ruler","paper for a chart"],
        steps:["Measure the height of each plant in centimetres.","Count the leaves on each.","Record today's numbers next to the earlier ones.","Make a simple bar chart of the three heights."],
        notebook:"Draw your bar chart. Was your prediction right? Say so honestly either way.",
        supervision:false},
     b:{read:"An investigation is only finished when the data is recorded, whether or not it matched what you expected. A prediction that turns out wrong is not a failed experiment; it is a result. Scientists write down what happened, not what they hoped would happen. Changing your record afterwards to look right is the one thing that is genuinely not allowed.",
        claim:"Write: 'My data shows ___. My prediction was ___, and the evidence ___ it.'"}},
  9:{a:{q:"Where has water moved dirt around my house?",
        materials:["shoes for outside","camera or paper and pencil"],
        steps:["Walk the yard after rain if you can.","Look under downspouts, at the bottom of slopes, and along paths.","Find three places where soil has clearly moved.","Photograph or sketch each one."],
        notebook:"Draw the clearest washout. Draw an arrow showing which way the water ran.",
        supervision:true},
     b:{read:"Moving water carries soil. Where it runs fast it picks material up; where it slows it drops what it was carrying. That is why a bare patch appears under a downspout and a fan of dirt collects where the ground flattens out. The same two processes shape a whole coastline, only larger and slower.",
        claim:"Write: 'Water changed ___ in my yard. My evidence is ___.'"}},
  10:{a:{q:"Can wind move soil too?",
        materials:["tray","dry sand and dry soil","drinking straw","safety glasses"],
        steps:["Spread dry soil in one half of the tray and dry sand in the other.","Wearing glasses, blow gently across each through the straw from the side.","Watch what moves first and how far.","Try again with the soil slightly damp."],
        notebook:"Draw the tray before and after. Which moved more, sand or soil? Wet or dry?",
        supervision:true},
     b:{read:"Wind moves the lightest, driest particles first. Damp soil sticks together and stays put, which is why bare dry ground blows away and planted ground does not. Ripples in dry dirt or sand are made the same way ripples form in a streambed, just with air doing the pushing instead of water.",
        claim:"Write: 'Wind moved the ___ more than the ___, because ___.'"}},
  11:{a:{q:"Does anything hold soil in place?",
        materials:["2 trays","soil","grass sod or a planted patch","watering can","2 catch pans"],
        steps:["Fill one tray with bare soil and one with soil that has grass or plants growing in it.","Prop both at the same slope over catch pans.","Pour the same amount of water down each.","Compare how muddy the water in each pan is."],
        notebook:"Draw both pans side by side. Which water was dirtier and why?",
        supervision:true},
     b:{read:"Roots hold soil the way threads hold cloth together. Plant cover also breaks the fall of raindrops before they hit bare ground. This is why farmers plant cover crops and why a bare hillside washes away in a storm while a grassy one does not. Preventing erosion is mostly a matter of keeping something growing.",
        claim:"Write: 'The ___ tray lost more soil. This shows that ___.'"}},
  12:{a:{q:"What can I actually see in a fossil?",
        materials:["real or replica fossils","hand lens","paper"],
        steps:["Look at each fossil with the lens before reading anything about it.","Draw exactly what you see, including the parts you do not understand.","Write down three things you observe and one thing you wonder.","Only then find out what the fossil is."],
        notebook:"Your careful drawing, with labels only for what you actually saw.",
        supervision:false},
     b:{read:"A fossil is evidence that something was once alive. The shape of a shell, the print of a leaf, the track of a foot - these were made by real organisms. Notice the difference between what you observe (this has ridges) and what you conclude (this was a shellfish). Both matter, but they are not the same kind of statement.",
        claim:"Write: 'I observed ___. From that I conclude ___.'"}},
  13:{a:{q:"What does this fossil tell me about the place it came from?",
        materials:["shell or marine fossil","map of Georgia","paper"],
        steps:["Look at the fossil and decide what kind of place that organism needed.","Find where that fossil was collected on the map.","Note whether that place is like that today.","Write what must have been different."],
        notebook:"Draw the fossil. Write one sentence about the environment it lived in.",
        supervision:false},
     b:{read:"Fossils tell you about places, not only about creatures. A shell fossil found far inland means that spot was once underwater. Fossil ferns mean it was once warm and wet. The organism needed a particular environment to live, so finding it somewhere is evidence about what that somewhere used to be like.",
        claim:"Write: 'This fossil is evidence that ___ used to be ___, because ___.'"}},
  14:{a:{q:"How does something become a fossil?",
        materials:["modelling clay","a shell or leaf","petroleum jelly","plaster of Paris (adult)","small cup"],
        steps:["Press the shell firmly into flattened clay and lift it straight out.","Look at the impression you made.","With an adult, mix plaster and pour it into the impression.","Let it set, then separate the two."],
        notebook:"Draw the three stages: shell, impression, and plaster copy.",
        supervision:true},
     b:{read:"Most living things never become fossils. It takes a particular sequence: the organism must be buried quickly, usually by sediment, before it rots or is eaten. Then the soft parts break down while the hard parts stay. Over time the surrounding sediment hardens around them. Quick burial is the part that almost never happens, which is why fossils are rare.",
        claim:"Write: 'For a fossil to form, first ___, then ___, then ___.'"}},
  15:{a:{q:"Can I build layers that show a sequence?",
        materials:["clear jar","sand","soil","gravel","small objects to bury","water"],
        steps:["Put down a layer of gravel, then soil, then sand, burying a small object between two layers.","Add each layer gently so they do not mix.","Look at the jar from the side.","Work out which layer was put down first."],
        notebook:"Draw your jar with the layers labelled 1st, 2nd, 3rd from the bottom up.",
        supervision:false},
     b:{read:"When layers of sediment settle one on top of another, the bottom layer got there first. That simple idea lets scientists put events in order without knowing any dates at all. If a shell sits between two layers, it arrived after the lower one and before the upper one. Sequence and age are different questions, and layering answers only the first.",
        claim:"Write: 'The ___ layer was there first, because ___.'"}},
  16:{a:{q:"Where are Georgia's five regions, and which one am I in?",
        materials:["outline map of Georgia","coloured pencils","atlas or reference"],
        steps:["Draw the five regions onto your map: Blue Ridge, Valley and Ridge, Appalachian Plateau, Piedmont, Coastal Plain.","Colour each one differently and make a key.","Mark your own town with a star.","Write which region you live in."],
        notebook:"Your finished map with a key and your town marked.",
        supervision:false},
     b:{read:"Georgia has five regions because it has five kinds of land. The Blue Ridge is mountainous and cool. The Appalachian Plateau is a small flat-topped corner in the northwest. Valley and Ridge is exactly what it sounds like. The Piedmont is rolling red-clay hills across the middle. The Coastal Plain is flat and sandy, running to the marshes and barrier islands.",
        claim:"Write: 'I live in the ___ region. I know because ___.'"}},
  17:{a:{q:"What lives up in the mountains?",
        materials:["reference books or printed pages","paper","pencils"],
        steps:["Find two plants and two animals of the Blue Ridge or Appalachian Plateau.","Draw each one.","Write one sentence per organism about what the mountain habitat gives it.","Note the elevation and typical temperature."],
        notebook:"A region page: name, land, two plants, two animals.",
        supervision:false},
     b:{read:"The Blue Ridge holds Georgia's highest ground, and height changes everything. It is cooler and wetter than the rest of the state, so it grows different trees and supports animals like black bears and trout that need cold water. The Appalachian Plateau in the far northwest corner is small, flat-topped and has caves.",
        claim:"Write: '___ can live in the Blue Ridge because it needs ___.'"}},
  18:{a:{q:"What does 'valley and ridge' actually look like?",
        materials:["modelling clay in two colours","paper","ruler"],
        steps:["Make several long flat clay strips and stack them.","Push the stack gently from both ends so it buckles into folds.","Look at it from the side.","Slice the top off level and look at the pattern."],
        notebook:"Draw your folded clay from the side and from above.",
        supervision:false},
     b:{read:"The Valley and Ridge region is made of long parallel ridges with valleys between them, running northeast to southwest. The rock layers there were folded long ago, and the harder layers stood up as ridges while softer ones wore down into valleys. Farms sit in the valleys where the soil is deeper.",
        claim:"Write: 'The ridges are higher because ___.'"}},
  19:{a:{q:"What is the ground like where I actually live?",
        materials:["trowel","white paper","hand lens","water"],
        steps:["Dig a small hole in a spot an adult approves.","Put a spoonful of the soil on white paper.","Describe its colour and feel.","Add water and see whether it rolls into a ball."],
        notebook:"Draw and describe your local soil. Is it sandy, clayey or loamy?",
        supervision:true},
     b:{read:"Most Georgians live in the Piedmont, the wide band of rolling hills across the middle of the state. Its red clay is famous, and the colour comes from iron in the soil. Piedmont clay holds water and packs hard, which is why it grows some crops well and drains badly. Atlanta, Macon and Athens all sit in it.",
        claim:"Write: 'My local soil is ___. My evidence is ___.'"}},
  20:{a:{q:"How is the coast different from everywhere else?",
        materials:["reference pages","paper","coloured pencils"],
        steps:["Find out what a salt marsh is and draw one.","List three animals that live there.","Find out what a barrier island does during a storm.","Draw the coastline with an island in front of the marsh."],
        notebook:"A coastal page: marsh, barrier island, three animals.",
        supervision:false},
     b:{read:"The Coastal Plain covers the southern half of Georgia and is flat, sandy and low. At its eastern edge, salt marshes sit behind barrier islands. The marsh is neither land nor open sea, and an enormous number of young fish and crabs grow up in it. The islands take the force of storms first, which is why they change shape year to year.",
        claim:"Write: 'The salt marsh matters because ___.'"}},
  21:{a:{q:"How well does camouflage actually work?",
        materials:["paper in several colours","scissors","a tree or patterned surface","timer"],
        steps:["Cut twenty paper moths, some matching the bark and some not.","Have someone pin them all on the tree while you look away.","Take thirty seconds to find as many as you can.","Count which colours you found and which you missed."],
        notebook:"A tally of moths found by colour. Which was hardest to see?",
        supervision:false},
     b:{read:"Camouflage means an animal's colour or pattern helps it avoid being seen. It works against predators looking for prey and also helps predators sneak up. It only works in the right place: a moth matching pale bark is obvious on dark bark. That is why camouflage ties an animal tightly to one kind of habitat.",
        claim:"Write: 'The ___ moths were hardest to find because ___.'"}},
  22:{a:{q:"What does an animal do when the food runs out?",
        materials:["paper","pencils","reference on black bears"],
        steps:["Draw a circle divided into twelve months.","Mark when a Georgia black bear eats heavily, and when it dens up.","Note what its body does during winter.","Write what would happen if it stayed active all winter."],
        notebook:"Your bear year wheel, labelled by month.",
        supervision:false},
     b:{read:"Hibernation is a way of surviving a season when food is scarce. The animal slows its heartbeat and breathing, lives off stored fat, and waits. It is not ordinary sleep. Georgia black bears den up rather than hibernating as deeply as northern bears do, because winters here are milder and food is not gone as completely.",
        claim:"Write: 'Hibernating helps a bear because ___.'"}},
  23:{a:{q:"Where do the birds go?",
        materials:["map of North America","string or coloured pencil","reference on one migratory bird"],
        steps:["Pick a bird that passes through Georgia.","Find where it spends summer and where it spends winter.","Draw the route on the map.","Estimate the distance."],
        notebook:"Your migration map with the route and distance marked.",
        supervision:false},
     b:{read:"Migration is moving with the seasons to stay where food is. Many birds breed in the north during summer, when insects are plentiful, then fly south before winter. Georgia sits along migration routes, so some birds pass through twice a year without staying. Migration costs enormous energy, which is only worth it because staying would cost more.",
        claim:"Write: 'This bird migrates because ___. My evidence is ___.'"}},
  24:{a:{q:"Can one animal survive by looking like another?",
        materials:["pictures of a monarch and a viceroy butterfly","paper","coloured pencils"],
        steps:["Draw both butterflies as carefully as you can.","Circle every difference you can find.","Read which one is unpleasant to eat.","Write why looking similar would help the other one."],
        notebook:"Both butterflies drawn side by side with differences circled.",
        supervision:false},
     b:{read:"Mimicry is when one animal resembles another, or resembles something else entirely, in a way that helps it survive. A harmless animal that looks like a harmful one may be left alone by predators that have learned to avoid the original. It only works while the copies stay rarer than the real thing.",
        claim:"Write: 'Mimicry helps the ___ because a predator ___.'"}},
  25:{a:{q:"Which Georgia animals belong where?",
        materials:["ten animal cards or drawings","your region map","paper"],
        steps:["Lay out your five regions.","Place each animal in the region where it lives.","For each, write the one feature that suits it there.","Check any you were unsure about."],
        notebook:"Your ten animals sorted by region, with a reason for each.",
        supervision:false},
     b:{read:"An organism thrives where its needs are met: the right temperature, the right food, the right water, the right shelter. Trout need cold fast water, so they live in mountain streams. Fiddler crabs need tidal mud, so they live in the marsh. Matching an animal to a place means matching its needs, not just its picture.",
        claim:"Write: 'The ___ lives in the ___ region because it needs ___.'"}},
  26:{a:{q:"What if I moved an animal to the wrong place?",
        materials:["your animal cards","paper"],
        steps:["Choose one marsh animal and one mountain animal.","Swap them on the map.","For each, list three specific problems it would face.","Decide which problem would matter first."],
        notebook:"Two lists of three problems, with the most urgent one circled.",
        supervision:false},
     b:{read:"Asking why an organism cannot live somewhere is often more revealing than asking why it can. A fiddler crab in the mountains has no tidal mud to burrow in, no salt water, and nothing it can eat. Each of those alone would be enough. This is why habitats matter: an animal is not merely near its habitat, it is fitted to it.",
        claim:"Write: 'A ___ could not survive in the ___ because ___.'"}},
  27:{a:{q:"Can I argue a claim properly?",
        materials:["your notebook from this unit","paper"],
        steps:["Pick any claim you made in the last three weeks.","Write the claim on one line.","Under it, write the evidence you actually collected.","Under that, write why the evidence supports the claim."],
        notebook:"One claim, its evidence, and the reasoning, clearly separated.",
        supervision:false},
     b:{read:"A claim is what you think is true. Evidence is what you observed. Reasoning is the sentence that connects them. People often give a claim and skip straight to arguing, or give evidence and assume the point is obvious. Writing all three separately makes it clear whether your argument actually holds together.",
        claim:"Write all three lines: Claim ___. Evidence ___. Reasoning ___."}},
  28:{a:{q:"What pollution can I find in one walk?",
        materials:["gloves","bag","notebook","adult"],
        steps:["Walk a set route with an adult.","Record every piece of litter and where it was.","Note anything in the air or water you can see or smell.","Tally the types."],
        notebook:"A tally table: type of pollution, where found, how much.",
        supervision:true},
     b:{read:"Pollution is anything added to air, land or water that harms living things. Some of it is obvious, like litter. Some is not, like runoff carrying fertiliser into a creek. Keeping a record of what you actually found, with the place and amount, turns a vague impression into evidence somebody could act on.",
        claim:"Write: 'The most common pollution on my route was ___. My record shows ___.'"}},
  29:{a:{q:"What does pollution do to an animal?",
        materials:["feather or cotton wool","cooking oil","dish of water","soap"],
        steps:["Float the feather on clean water and note how it behaves.","Add a spoon of oil to the water and dip the feather.","Try to clean it with water alone, then with soap.","Note how much effort it took."],
        notebook:"Draw the feather before, oiled, and after cleaning.",
        supervision:true},
     b:{read:"Oil coats feathers so they can no longer trap air, and a bird that cannot trap air cannot stay warm or float. This is why an oil spill kills birds that were never poisoned by it. Pollution often works this way: not by being eaten, but by ruining something the animal depended on.",
        claim:"Write: 'Oil harms a bird because ___. My evidence is ___.'"}},
  30:{a:{q:"What is in a week of our rubbish?",
        materials:["a week of household waste (clean)","gloves","scales if available","paper"],
        steps:["Sort the waste into paper, plastic, metal, glass, food and other.","Weigh or estimate each pile.","Work out which pile is biggest.","Find out which of these your area actually recycles."],
        notebook:"A chart of the six piles by size, with recyclable ones marked.",
        supervision:true},
     b:{read:"Recycling means using a material again instead of taking new material out of the ground or forest. It works best for metal and glass, which can be melted and reused many times. Paper can be recycled a limited number of times. Not every plastic is accepted everywhere, which is why knowing your own area's rules matters more than a general rule.",
        claim:"Write: 'Our biggest waste pile was ___. Of it, ___ could be recycled here.'"}},
  31:{a:{q:"Can we actually use less of something?",
        materials:["notebook","whatever you choose to measure"],
        steps:["Pick one thing to reduce for a week: water, electricity, paper or packaging.","Measure a normal week first.","Make one specific change and keep it.","Measure the second week the same way."],
        notebook:"Two weeks of numbers side by side, and the change you made.",
        supervision:false},
     b:{read:"Conservation means using less so there is more left. It is different from recycling, which deals with what you have already used. Turning a tap off while brushing saves water that was never dirtied in the first place. Small changes only matter when they are measured and kept - which is why this week asks for numbers, not intentions.",
        claim:"Write: 'I changed ___. My measurements show ___.'"}},
  32:{a:{q:"Where does heat come from?",
        materials:["hands","a sunny window","a candle (adult only)","paper"],
        steps:["Hold your hands in sunlight and note what you feel.","Rub your palms together fast for ten seconds and note what you feel.","With an adult, observe a candle from a safe distance.","Write what all three have in common."],
        notebook:"Three drawings: sun, rubbing hands, flame. One sentence on what each does.",
        supervision:true},
     b:{read:"Heat comes from several sources. Sunlight carries energy across space and warms whatever absorbs it. Friction turns movement into heat, which is why rubbing warms your hands and why brakes get hot. Burning releases heat stored in a fuel. Different sources, same result: something gets warmer.",
        claim:"Write: 'Three sources of heat are ___, ___ and ___.'"}},
  33:{a:{q:"Can I read a thermometer accurately?",
        materials:["thermometer","cup of cool water","cup of warm water","room air","paper"],
        steps:["Read the room temperature and write it with its unit.","Put the thermometer in cool water, wait a full minute, and read again.","Repeat with warm water.","Read each one twice to check you get the same number."],
        notebook:"A table: what was measured, temperature, unit. Three rows.",
        supervision:true},
     b:{read:"A thermometer turns a feeling into a number. That matters because feelings differ between people while numbers do not. Two rules make readings trustworthy: wait until the reading stops moving, and read at eye level. Always write the unit, because 20 degrees Celsius and 20 degrees Fahrenheit are very different things.",
        claim:"Write: 'The ___ water was ___ degrees, which is ___ than the room.'"}},
  34:{a:{q:"Does colour change how much something heats up?",
        materials:["black paper","white paper","2 thermometers","sunny spot","timer"],
        steps:["Put a thermometer under each sheet in full sun.","Record both temperatures at the start.","Record again every five minutes for half an hour.","Make a table of both sets of readings."],
        notebook:"Your table of readings, and a line for each colour on one chart.",
        supervision:true},
     b:{read:"Dark surfaces absorb more sunlight and reflect less, so they warm faster. Light surfaces reflect more away. This is why a black car is hotter inside than a white one on the same day, and why people in hot places often wear light colours and paint roofs white.",
        claim:"Write: 'The ___ paper got hotter. My data shows ___ degrees difference.'"}},
  35:{a:{q:"Which way does heat move?",
        materials:["cup of warm water","metal spoon","thermometer","timer"],
        steps:["Measure the water temperature and the spoon temperature separately.","Stand the spoon in the water.","After five minutes measure both again.","Write which got warmer and which got cooler."],
        notebook:"Four numbers in a table: each item, before and after.",
        supervision:true},
     b:{read:"Heat always moves from the warmer thing to the cooler thing, never the other way. The spoon warms and the water cools slightly, and they move toward the same temperature. Nothing pushes the heat; it simply spreads. This is why a cold drink warms up in a room rather than the room getting colder.",
        claim:"Write: 'Heat moved from ___ to ___. My evidence is ___.'"}},
  36:{a:{q:"What do two weeks of numbers prove?",
        materials:["all your temperature tables","graph paper","ruler"],
        steps:["Gather every temperature reading you have taken this unit.","Plot the sun and shade readings on one chart.","Mark the biggest difference you recorded.","Write the one thing your data proves most clearly."],
        notebook:"Your finished chart, with the strongest result circled.",
        supervision:false},
     b:{read:"A single reading is an anecdote; a table of readings is evidence. Charting them makes a pattern visible that individual numbers hide. When you can point at a chart and say what it shows, and also say what it does not show, you are doing what a scientist does. The limits of your data are part of your result.",
        claim:"Write: 'My data proves ___. It does not prove ___.'"}}
  };

  const Y5 = {
  1:{a:{q:"Does moving water build up or wear down?",
        materials:["shallow tray","sand","water in a jug","books to prop the tray"],
        steps:["Build a sloped hill of damp sand at one end of the propped tray.","Pour water slowly from the top and watch where sand leaves and where it lands.","Mark the spot that lost the most sand and the spot that gained the most.","Repeat with a steeper slope."],
        notebook:"Draw the tray before and after. Label one area 'destructive' and one 'constructive'.",
        supervision:false},
     b:{read:"Constructive processes build land up; destructive processes wear it down. Deposition builds a delta. Weathering and erosion wear down a mountain. Most landscapes show both at once, in different places, driven by the same moving water. Organisms count too: roots split rock, and burrowing animals move soil.",
        claim:"Claim, evidence, reasoning: was your sand hill mostly built up or worn down, and how do you know?"}},
  2:{a:{q:"Can freezing water break rock?",
        materials:["small plastic bottle with cap","water","freezer","porous rock or plaster block","zip bag"],
        steps:["Fill the bottle to the very top with water and cap it tightly.","Put it in a bag and freeze overnight.","Observe what happened to the bottle.","If you have a soaked porous rock, freeze and thaw it several times and look for flaking."],
        notebook:"Draw the bottle before and after. Explain what the ice did and why.",
        supervision:false},
     b:{read:"Water expands when it freezes. Water seeps into cracks in rock, freezes, and pushes the crack wider. Thaw, refill, refreeze, and the crack grows. Repeated over many winters this breaks solid rock into smaller pieces. It is called mechanical weathering because the rock is broken apart without being chemically changed.",
        claim:"Write a claim about freeze-thaw with the evidence from your bottle."}},
  3:{a:{q:"Where does a river drop what it is carrying?",
        materials:["tray","sand and fine silt","water","block to prop one end","catch basin"],
        steps:["Make a channel in sloped sand leading into a flat area of standing water.","Pour a sand-and-water mixture down the channel steadily.","Watch where the material stops moving.","Note the shape it forms."],
        notebook:"Draw the shape that formed where the channel met the still water. Name it.",
        supervision:false},
     b:{read:"Moving water carries sediment; slow water cannot. Where a river meets a lake or sea it slows abruptly and drops its load, building a delta. Heavier particles drop first and lighter ones travel further out, which sorts the deposit by size. The Mississippi delta is this process at continental scale.",
        claim:"Claim, evidence, reasoning about why the material stopped where it did."}},
  4:{a:{q:"What made each of these four landforms?",
        materials:["pictures of a delta, a dune, a canyon, a volcano","paper"],
        steps:["For each landform write whether it was built up, worn down, or both.","Name the process responsible: deposition, erosion, weathering, or eruption.","Name what did the work: water, wind, ice, organisms, or the earth itself.","Rank them from fastest-forming to slowest."],
        notebook:"A four-row table: landform, process, agent, built up or worn down.",
        supervision:false},
     b:{read:"A canyon is carved: water removed rock over a long time. A dune is deposited: wind dropped sand where it slowed. A delta is deposited by water. A volcano is built by material erupting from below. Reading a landform means asking what moved, in which direction, and what moved it.",
        claim:"Pick the landform you are most confident about and argue it fully."}},
  5:{a:{q:"Can a model tell me something real?",
        materials:["stream table or long tray","sand","water supply","catch bucket","timer"],
        steps:["Set up a sloped stream table with an even sand surface.","Run a steady trickle of water for two minutes.","Photograph or sketch the channel that forms.","Note three ways your model is unlike a real river."],
        notebook:"Your channel sketch, plus the list of three limits of the model.",
        supervision:false},
     b:{read:"A model is a simplified stand-in used to study something too big, slow or dangerous to handle directly. Its value is that you can change one thing and watch. Its danger is forgetting what it leaves out. A stream table has no rock, no plants and no seasons, so it shows how channels form but not how long that takes.",
        claim:"Write what your model showed well and what it could not show."}},
  6:{a:{q:"How much did it actually change?",
        materials:["stream table","ruler","water","timer","graph paper"],
        steps:["Measure the channel width at three fixed points before you start.","Run water for one minute and measure again at the same points.","Repeat for three one-minute runs, recording each time.","Convert any fractions of a centimetre to decimals."],
        notebook:"A table of nine measurements and a line graph of change over time.",
        supervision:false},
     b:{read:"Saying a channel got wider is an observation. Saying it went from 1.5 cm to 3.25 cm in three minutes is data. Data lets you compare runs, spot a trend, and let someone else check you. Georgia's standards ask you to convert fractions to decimals in exactly this kind of calculation, because a table of mixed forms is hard to compare.",
        claim:"State the rate of change you measured and what it predicts for a longer run."}},
  7:{a:{q:"At what point does a levee fail?",
        materials:["stream table or tray","sand","small dam or levee material","water","measuring cup"],
        steps:["Build a levee along one side of your channel.","Add water in measured amounts, recording each addition.","Note the volume at which water first tops or breaches the levee.","Rebuild it higher and repeat."],
        notebook:"Record the failure point for both levee heights. Draw how it failed.",
        supervision:false},
     b:{read:"Levees, dams and storm drains are attempts to limit destructive processes. They work up to a designed limit and then fail, often suddenly. Engineers design for a flood of a certain size, because designing for every possible flood is not affordable. Knowing the limit is part of the design, not a flaw in it.",
        claim:"Argue from your data what raising a levee does and does not accomplish."}},
  8:{a:{q:"Can a beach be rebuilt?",
        materials:["tray","sand","water","small blocks for structures","spoon for adding sand"],
        steps:["Build a beach and make waves by rocking the tray gently and steadily.","Record how the beach changes over fifty waves.","Add sand to rebuild it (this is beach renourishment) and repeat.","Try again with a barrier in the water."],
        notebook:"Three sketches: original beach, eroded beach, renourished beach.",
        supervision:false},
     b:{read:"Georgia's barrier islands take the force of storms before the mainland does, and they naturally shift. Beach renourishment pumps sand back onto an eroded beach. It works, but it is temporary, because the process that removed the sand has not stopped. Communities weigh that recurring cost against what the beach protects.",
        claim:"Argue whether renourishment solves the problem or delays it, using your model."}},
  9:{a:{q:"What makes a grouping useful rather than arbitrary?",
        materials:["a box of about 20 mixed objects","paper"],
        steps:["Sort the objects into groups any way you like and write your rule.","Now re-sort them by a completely different rule.","Ask someone else to sort them without seeing your rules.","Compare: which rule would let a stranger predict something?"],
        notebook:"Both of your sorting rules, and which was more useful and why.",
        supervision:false},
     b:{read:"Any pile can be sorted many ways. Scientific classification chooses groupings that carry information: if you know an organism is a mammal you can predict it has hair, a backbone and warm blood. Sorting by colour predicts nothing. The test of a good group is whether membership tells you anything you did not already see.",
        claim:"Argue which of your two sorting rules was more scientific, and why."}},
  10:{a:{q:"Can I place an unfamiliar organism?",
        materials:["organism cards or pictures","paper"],
        steps:["Sort twenty organism cards into the largest sensible groups first.","Split each group into smaller ones.","Keep going until each card is alone or with near-identical cards.","Write the question you asked at each split."],
        notebook:"Your grouping tree with the question written at each branch.",
        supervision:false},
     b:{read:"Classification is nested: broad groups contain narrower ones. Kingdom, phylum, class, order, family, genus, species runs from most inclusive to least. Each level is defined by shared characteristics, so each step down adds information. Two organisms in the same genus have far more in common than two in the same kingdom.",
        claim:"Explain what someone learns about an organism from each level of your tree."}},
  11:{a:{q:"Backbone or no backbone?",
        materials:["organism pictures","paper","hand lens if you have specimens"],
        steps:["Sort twenty animals into vertebrate and invertebrate.","Within vertebrates, split into fish, amphibian, reptile, bird and mammal.","For each group write the feature that defines it.","Note any animal that was hard to place and why."],
        notebook:"Your two-level sort with defining features written for each group.",
        supervision:false},
     b:{read:"A backbone is a major dividing line because so much follows from it: an internal skeleton allows size, and supports a particular nervous system. Within vertebrates, the classes are separated by features like skin covering, egg type and temperature regulation. The hard-to-place animals are usually the interesting ones.",
        claim:"Argue why one specific animal belongs in the class you assigned it."}},
  12:{a:{q:"Can a stranger use my key?",
        materials:["ten organisms or pictures","paper","a willing tester"],
        steps:["Write a dichotomous key: each step offers exactly two choices.","Every choice must be observable, not something you have to know already.","Test it yourself on all ten.","Hand it to someone else and watch where they get stuck."],
        notebook:"Your key, plus the step your tester struggled with and how you fixed it.",
        supervision:false},
     b:{read:"A dichotomous key splits a group in two at every step until one organism remains. The quality test is whether someone unfamiliar with the organisms can follow it. That forces every question to be about something visible - 'wings or no wings', not 'is it a strong flier'. Ambiguity in a key shows up immediately when a stranger uses it.",
        claim:"Explain one change you made after testing, and what evidence prompted it."}},
  13:{a:{q:"Which of my family's traits were handed down?",
        materials:["paper","willing family members","mirror"],
        steps:["List ten of your own physical features.","For each, check whether a parent or grandparent has it.","Mark each as probably inherited or probably not.","Note any you cannot decide about."],
        notebook:"Your ten-feature table with the inherited ones marked.",
        supervision:false},
     b:{read:"An inherited trait is passed from parents through reproduction - eye colour, hair type, the shape of a nose. You did not do anything to acquire it. Some traits are influenced by environment as well, so height depends on both what was inherited and what was eaten. The clean test is whether it was present before any learning happened.",
        claim:"Argue for one trait being inherited, using your family evidence."}},
  14:{a:{q:"What did this animal have to learn?",
        materials:["a pet, sibling, or observation of an animal","notebook","timer"],
        steps:["Watch one animal or person for fifteen minutes.","Write down every behaviour you observe.","Mark each as something it could do from birth or something it must have learned.","Note what evidence made you decide."],
        notebook:"Your behaviour list with each one classified and justified.",
        supervision:false},
     b:{read:"A learned behaviour is acquired through experience or teaching. A dog sitting on command learned it; a dog panting did not. The distinction is not always obvious, because some behaviours are instinctive but only appear at a certain age. The useful question is whether the behaviour would appear in an individual raised with no example to copy.",
        claim:"Argue for one behaviour being learned, with the evidence you observed."}},
  15:{a:{q:"Can I sort twenty examples correctly?",
        materials:["twenty written examples","paper"],
        steps:["Sort all twenty into inherited traits and learned behaviours.","Put any you are unsure about in a third pile.","For the unsure pile, write what you would need to know to decide.","Check your sort against a reference."],
        notebook:"Your three piles, with a written test for each unsure item.",
        supervision:false},
     b:{read:"The hard cases teach the most. A bird's song is partly inherited and partly learned from adults, which is why isolated birds sing incompletely. Admitting a case is mixed is more accurate than forcing it into one box. Being able to say what evidence would settle a question is itself a scientific skill.",
        claim:"Take one unsure example and describe the investigation that would settle it."}},
  16:{a:{q:"How much do offspring vary?",
        materials:["a packet of the same seed type","ruler","paper","scales if available"],
        steps:["Measure twenty seeds of the same kind: length in millimetres.","Convert any fractional readings to decimals.","Make a tally of the sizes.","Find the range and the most common size."],
        notebook:"Your tally chart, the range, and the most common value.",
        supervision:false},
     b:{read:"Offspring resemble their parents but are not identical to them or to each other. Measure enough of them and the variation forms a pattern, usually clustered around a middle value with fewer at the extremes. This is why predicting offspring traits is about likelihood rather than certainty, even before any genetics is introduced.",
        claim:"State what your data predicts about the next seed you measure, and how confident you are."}},
  17:{a:{q:"What can I actually see through a magnifier?",
        materials:["onion","slide and cover slip or clear tape","hand lens or microscope","water dropper","iodine (adult, optional)"],
        steps:["Peel a thin transparent layer from between onion segments.","Lay it flat on a slide with a drop of water and cover it.","Look at low power first, then higher.","Draw exactly what you see, not what you expect."],
        notebook:"Your drawing at the magnification you used, labelled with what you observed.",
        supervision:true},
     b:{read:"Living things are built from cells, which are too small to see unaided. Onion skin is a good first slide because its cells are large, regular and nearly transparent. Notice the repeating boxes: that pattern is the point. Drawing what you actually see, including the parts you cannot identify, is the habit that matters most here.",
        claim:"Describe what you observed and what you can and cannot conclude from it."}},
  18:{a:{q:"What parts does a plant cell have?",
        materials:["elodea or other aquatic plant leaf","slide","water","microscope or strong lens"],
        steps:["Mount a single leaf in water and cover it.","Look for the outer boundary of each cell and the green bodies inside.","Sketch three adjacent cells.","Label the wall, the green bodies and any large clear space."],
        notebook:"Three adjacent cells drawn and labelled from your own observation.",
        supervision:true},
     b:{read:"Plant cells have a rigid cell wall outside the membrane, which is why plant tissue holds its shape. They contain chloroplasts, the green bodies where light is captured, and usually one large vacuole storing water. The wall, the chloroplasts and the large vacuole are the three parts an animal cell will not have.",
        claim:"Argue from your slide that this was a plant cell."}},
  19:{a:{q:"How is an animal cell different?",
        materials:["cheek cell sample (adult supervision)","slide","methylene blue or iodine","microscope"],
        steps:["With an adult, take a gentle inner-cheek sample and smear it on a slide.","Add one drop of stain and cover.","Find a single separated cell.","Draw it and label the boundary and the nucleus."],
        notebook:"One animal cell drawn beside your plant cell from last week.",
        supervision:true},
     b:{read:"Animal cells have a membrane but no wall, so they are flexible and rounded rather than boxy. They have no chloroplasts, because animals do not capture light, and no single large vacuole. Both cell types have a nucleus and cytoplasm. Placing the two drawings side by side makes the differences obvious in a way a list does not.",
        claim:"Compare your two drawings and argue which differences are real rather than artefacts of the slide."}},
  20:{a:{q:"Is every living thing made of many cells?",
        materials:["pond or puddle water","slide","microscope","dropper"],
        steps:["Put one drop of pond water on a slide and cover it.","Scan slowly at low power for anything moving.","Watch one organism for a full minute.","Decide whether it is one cell or many, and say why."],
        notebook:"Draw one organism you found and record how it moved.",
        supervision:true},
     b:{read:"Some organisms are a single cell that does everything: feeding, moving, reproducing. Others are multicellular, with cells specialised for different jobs. A single-celled organism has no room for specialised parts, which limits its size. Multicellularity is what makes a leaf, a muscle or a nerve possible.",
        claim:"Argue whether your organism was single-celled or multicellular, from what you observed."}},
  21:{a:{q:"Can I get yeast to do something measurable?",
        materials:["dry yeast","sugar","warm water","3 bottles","3 balloons","thermometer"],
        steps:["Set up three bottles: yeast with sugar and warm water, yeast with warm water only, sugar and warm water only.","Stretch a balloon over each neck.","Record balloon size every five minutes for half an hour.","Keep the water temperature the same for all three."],
        notebook:"A table of balloon size over time for all three bottles.",
        supervision:false},
     b:{read:"Yeast is a single-celled fungus. Given sugar it produces carbon dioxide gas, which is what raises bread and inflates your balloon. The bottle with no sugar shows the yeast needs food; the bottle with no yeast shows the sugar does nothing alone. Those two are controls, and without them the first result proves much less.",
        claim:"Argue what caused the gas, using all three bottles as evidence."}},
  22:{a:{q:"What conditions does mould need?",
        materials:["bread","4 sealed bags","water","fridge","dark and light spots"],
        steps:["Seal four bread slices: dry and warm, damp and warm, damp and cold, damp and dark.","Label each with the date and conditions.","Observe daily through the sealed bag for a week - do not open them.","Record what appears and when."],
        notebook:"A daily observation log for all four bags.",
        supervision:true},
     b:{read:"Mould is a fungus that spoils food and can cause illness. It needs moisture and warmth, which is why refrigeration and drying preserve food. Keeping the bags sealed matters for safety: mould spores should not be released indoors, and the investigation works perfectly well through the plastic.",
        claim:"Argue which condition mattered most, using your four bags as evidence."}},
  23:{a:{q:"Does handwashing actually do anything?",
        materials:["glitter or flour","hand lotion","soap","water","paper towels"],
        steps:["Coat hands lightly in lotion then glitter - this stands in for microbes.","Try removing it with a dry wipe, then cold water, then soap and warm water for twenty seconds.","Photograph or record what remains after each.","Note where the last traces hide."],
        notebook:"Three records of what remained, and where the stubborn spots were.",
        supervision:false},
     b:{read:"Microorganisms are neither simply good nor simply bad. The same broad group includes the bacteria that make yogurt and help digestion, and the ones that cause illness. Soap works by loosening what is stuck to skin so water can carry it away, which is why twenty seconds of soap beats a rinse.",
        claim:"Argue from your evidence which washing method worked, and name the limits of glitter as a stand-in for microbes."}},
  24:{a:{q:"Which of these changes can I undo?",
        materials:["sand","salt","water","iron filings or paper clips","cups","magnet","spoon"],
        steps:["Mix sand and water; try to separate them again.","Dissolve salt in water; try to get the salt back.","Mix iron filings with sand; try a magnet.","Record which separations worked and how."],
        notebook:"A table: mixture, separation method, did it work.",
        supervision:false},
     b:{read:"A physical change alters form but not the substance itself. Mixing, dissolving, cutting and changing state are physical, because the original material is still there and can in principle be recovered. That recoverability is the practical test: if you can get it back out, nothing new was made.",
        claim:"Argue that one of your mixtures underwent a physical change, with the evidence."}},
  25:{a:{q:"How many ways can I separate a mixture?",
        materials:["salt water","sand water","filter paper or coffee filter","shallow dish","magnet","sunny spot"],
        steps:["Filter the sand and water. Record what stayed and what passed through.","Leave the salt water in a shallow dish in the sun for two days.","Use a magnet on a dry iron-and-sand mixture.","Match each method to the property it exploits."],
        notebook:"Three methods, each with the property it depends on.",
        supervision:false},
     b:{read:"Separation methods exploit differences in properties. Filtering uses particle size. Evaporation uses different boiling points. A magnet uses magnetism. Choosing a method means asking what is different about the two things you want apart - which is why knowing properties is practically useful and not just vocabulary.",
        claim:"Explain which property each of your three methods used."}},
  26:{a:{q:"What does temperature do to water?",
        materials:["ice","beaker or heatproof cup","thermometer","heat source (adult)","timer"],
        steps:["Put ice in the cup with the thermometer and record the starting temperature.","With an adult, warm it slowly, recording temperature every minute.","Note what the temperature does while the ice is melting.","Continue until it boils, recording throughout."],
        notebook:"A line graph of temperature against time. Mark where the ice melted.",
        supervision:true},
     b:{read:"Water changes state at particular temperatures. Notice that while ice is melting, the temperature stays put even though heat is still going in: that energy is being used to break the particles free rather than to raise the temperature. The particles are too small to see, but their movement is what temperature measures.",
        claim:"Argue from your graph that state change is caused by temperature, and explain the flat part."}},
  27:{a:{q:"Where does water go, and does it come back?",
        materials:["2 identical cups of water","plastic wrap","cold glass","warm room","marker"],
        steps:["Mark the water level in both cups. Cover one, leave one open.","Leave both for three days and re-mark the levels.","Separately, breathe on or set a cold glass in warm air and watch its outside.","Record both results."],
        notebook:"Both cup levels over three days, plus what appeared on the cold glass.",
        supervision:false},
     b:{read:"Evaporation is liquid becoming gas at the surface; condensation is gas becoming liquid on a cool surface. The covered cup loses little because the vapour has nowhere to go and condenses back. Water on the outside of a cold glass did not leak through it - it came out of the air.",
        claim:"Argue where the water from the open cup went, and where the water on the glass came from."}},
  28:{a:{q:"Did a chemical change happen here?",
        materials:["vinegar","baking soda","milk","food colouring","steel wool","salt","cups","thermometer","adult"],
        steps:["At each of five stations, combine the materials as directed and observe for two minutes.","For each, record colour change, gas, temperature change, odour, or apparent new substance.","Judge each station chemical or physical.","State which piece of evidence decided it."],
        notebook:"Five stations, five evidence records, five judgements with reasons.",
        supervision:true},
     b:{read:"A chemical change produces a new substance, and there are five common signs: colour change, gas produced, temperature change, odour, or a solid appearing from liquids. Any one of these is a hint; more than one is strong evidence. Bubbles alone are not conclusive, since boiling makes bubbles without any new substance.",
        claim:"Pick your most confident station and argue it fully, naming which evidence was decisive."}},
  29:{a:{q:"What is static electricity?",
        materials:["balloon","wool or hair","small paper pieces","pepper","dry day"],
        steps:["Rub the balloon on wool or hair for twenty seconds.","Hold it over small paper pieces and record what happens.","Try it over pepper and over a thin stream of water from a tap.","Try again without rubbing it first."],
        notebook:"Three results with and without rubbing. What did rubbing change?",
        supervision:false},
     b:{read:"Rubbing moves charge from one material to the other, leaving both charged. Charged objects attract uncharged light ones, which is why the balloon lifts paper and bends water. This is naturally occurring electricity - lightning is the same thing at enormous scale. It is not harnessed, because it discharges all at once rather than flowing steadily.",
        claim:"Argue what rubbing did, from your evidence, and how static differs from mains electricity."}},
  30:{a:{q:"What has to be true before the bulb lights?",
        materials:["battery","bulb in holder","two wires","tape"],
        steps:["Try to light the bulb with one wire. Record what happens.","Add the second wire to complete a loop from one battery end to the other.","Once lit, disconnect one point at a time and note the effect.","Draw the arrangement that worked."],
        notebook:"Your circuit diagram, with every part labelled.",
        supervision:false},
     b:{read:"A circuit must be a complete loop from one terminal of the source, through the load, and back to the other terminal. Break it anywhere and current stops everywhere. The necessary parts are a source of energy, a conducting path, and a load that uses the energy. There is no partial credit in a loop.",
        claim:"Name the necessary parts and argue from your test that each one is required."}},
  31:{a:{q:"How do I control the flow?",
        materials:["battery","bulb","three wires","paper clip","two paper fasteners","cardboard"],
        steps:["Build a switch: two fasteners in cardboard bridged by a paper clip.","Insert the switch into your working circuit.","Test that the bulb responds to the switch.","Add a second bulb in the same loop and note the brightness."],
        notebook:"Your circuit with the switch drawn, plus what happened with two bulbs.",
        supervision:false},
     b:{read:"A switch is simply a gap you can open and close on purpose. In a series circuit, everything sits on one loop, so the current passes through every component in turn - which is why adding a second bulb dims both, and why one break stops everything. Every light in your house has a switch doing exactly this.",
        claim:"Explain what happened to brightness with two bulbs, and why."}},
  32:{a:{q:"What lets electricity through?",
        materials:["working circuit with a gap","twenty household materials","paper"],
        steps:["Leave a gap in your circuit with two free wire ends.","Touch each material across the gap and record whether the bulb lights.","Test twenty items: metals, plastics, wood, water, pencil lead, fabric.","Sort your results into conductors and insulators."],
        notebook:"A twenty-row table: material, lit or not, conductor or insulator.",
        supervision:false},
     b:{read:"Conductors let current pass; insulators do not. Most metals conduct, which is why wires are metal. Plastic, rubber, glass and dry wood insulate, which is why wires are coated in plastic. The pairing is deliberate: every cable in your house is a conductor wrapped in an insulator, and both parts are doing a job.",
        claim:"State the pattern in your results and predict a material you did not test."}},
  33:{a:{q:"What does a magnet do at a distance?",
        materials:["two bar magnets","paper clips","ruler","paper"],
        steps:["Bring one magnet slowly toward a paper clip and record the distance at which it first moves.","Repeat through paper, then through a book.","Bring two magnets together, then flip one and repeat.","Record attraction and repulsion."],
        notebook:"Your distance measurements and what happened with poles aligned and reversed.",
        supervision:false},
     b:{read:"A magnet acts through space without touching, and through non-magnetic materials. Every magnet has two poles: like poles repel, unlike attract. The region where the force acts is called the field. That it works through paper and through a book is evidence the field is not blocked by ordinary matter.",
        claim:"Argue from your measurements that magnetic force acts at a distance and weakens with it."}},
  34:{a:{q:"What shape is the field?",
        materials:["bar magnet","iron filings in a sealed bag or shaker","paper","compass"],
        steps:["Lay paper over the magnet and sprinkle filings evenly.","Tap the paper gently and observe the pattern.","Sketch the pattern exactly.","Walk a compass around the magnet and note where the needle points."],
        notebook:"Your field sketch with the compass directions marked at six points.",
        supervision:true},
     b:{read:"Iron filings line up along the field, making its shape visible: lines curving from one pole to the other, densest where the field is strongest. A compass needle is itself a small magnet, so it turns to align with the field wherever you put it. The field was always there; the filings only made it visible.",
        claim:"Argue where the field is strongest, from the pattern you observed."}},
  35:{a:{q:"Can electricity make a magnet?",
        materials:["iron nail","insulated wire","battery","paper clips","tape"],
        steps:["Wind twenty turns of wire tightly around the nail.","Connect both ends to the battery briefly and try to pick up paper clips.","Count how many it holds.","Disconnect and count again."],
        notebook:"Clips held while connected and while disconnected. What does that show?",
        supervision:true},
     b:{read:"An electric current produces a magnetic field, so a coil of wire around iron becomes a magnet while current flows. Unlike a permanent magnet, it can be switched off, and its strength can be changed. That controllability is the whole reason electromagnets are used in motors, doorbells, speakers and scrapyard cranes.",
        claim:"Argue how an electromagnet differs from a permanent magnet, using your two counts as evidence."}},
  36:{a:{q:"What makes an electromagnet stronger?",
        materials:["nail","wire","batteries","paper clips","paper"],
        steps:["Test 10, 20 and 30 turns of wire, counting clips held each time.","Test one battery and two batteries at the same turn count (brief connections only).","Test with and without the iron nail core.","Change only one variable at a time."],
        notebook:"Three comparisons, each with numbers, and a statement of what changed.",
        supervision:true},
     b:{read:"Three things increase an electromagnet's strength: more turns of wire, more current, and an iron core. Testing them one at a time is what makes the result trustworthy - change two things and you cannot say which mattered. This is the whole method of the year in one experiment: one variable, measured, recorded honestly.",
        claim:"State all three variables with your evidence for each, and name the one you tested most carefully."}}
  };

  function lessonFor(grade, week, day){
    const table = grade==="y5" ? Y5 : Y3;
    const wk = table[week] || table[1];
    const d  = (day==="B"||day==="b") ? "b" : "a";
    const L  = wk[d] || {};
    const spine = window.__CURR[grade==="y5" ? "SCI_Y5" : "SCI_Y3"];
    const meta  = spine ? spine.WEEKS.find(w=>w.n===week) : null;
    return Object.assign({
      id: "sci-"+grade+"-w"+week+"-"+d,
      week: week, day: d==="a" ? "A" : "B",
      kind: d==="a" ? "lab" : "explain",
      title: meta ? meta.title : ("Week "+week),
      standard: meta ? meta.standard : "",
      supervision: !!L.supervision
    }, L);
  }

  /* Everything a parent needs to buy or gather, per unit. */
  function materialsForUnit(grade, unitN){
    const spine = window.__CURR[grade==="y5" ? "SCI_Y5" : "SCI_Y3"];
    if(!spine) return [];
    const weeks = spine.WEEKS.filter(w=>w.unit===unitN).map(w=>w.n);
    const seen = {}, out = [];
    weeks.forEach(wn=>{
      const L = lessonFor(grade, wn, "A");
      (L.materials||[]).forEach(m=>{
        const k = m.toLowerCase();
        if(!seen[k]){ seen[k]=1; out.push(m); }
      });
    });
    return out;
  }

  /* Weeks in a unit that need an adult in the room. */
  function supervisedWeeks(grade, unitN){
    const spine = window.__CURR[grade==="y5" ? "SCI_Y5" : "SCI_Y3"];
    if(!spine) return [];
    return spine.WEEKS.filter(w=>w.unit===unitN)
      .filter(w=>lessonFor(grade, w.n, "A").supervision)
      .map(w=>w.n);
  }

  window.__CURR = window.__CURR || {};
  window.__CURR.SCI_LESSONS = {Y3, Y5, lessonFor, materialsForUnit, supervisedWeeks};
})();
